# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVRk3v9VK4Lv12FQqol8UOJMCAitr5Pl
"""

import numpy as np
sensor_data=np.matrix([
    [12, 15, 14, 10, 13],
    [20, 22, 19, 18, 21],
    [30, 28, 27, 29, 31],
    [25, 24, 26, 23, 22]
])
avg_per_machine=np.mean(sensor_data,axis=1)
print("average reading per machine:")
print(avg_per_machine)
max_per_interval=np.max(sensor_data,axis=0)
print("maximum reading per interval:")
print(max_per_interval)

normalized_data=sensor_data/max_per_interval
print("normalized data:")
print(normalized_data)
machine_above_20=np.where(avg_per_machine>20)
print("machone above 20:")
print(machine_above_20)
reshaped_matrix=sensor_data.reshape(5,4)
print("reshaped matrix:")
print(reshaped_matrix)

import numpy as np
A = np.random.randint(1, 51, (3,3))
B = np.random.randint(1, 51, (3,3))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

matrix_mult = A @ B
print("\nMatrix Multiplication:\n", matrix_mult)

element_mult = A * B
print("\nElement-wise Multiplication:\n", element_mult)

greater_than_100 = matrix_mult[matrix_mult > 100]
print("\nElements greater than 100:\n", greater_than_100)

A[A < 10] = 0
B[B < 10] = 0

print("\nMatrix A after replacing values <10:\n", A)
print("\nMatrix B after replacing values <10:\n", B)

stacked_matrix = np.vstack((A, B))
print("\nVertically Stacked Matrix:\n", stacked_matrix)

import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, None, 2400, 5200, 15000]
}
df = pd.DataFrame(sales_data)

print("Dataset:")
print(df)

print("\nMissing Values:")
print(df.isnull())

df["Amount"] = df["Amount"].fillna(df["Amount"].mean())

print("\nDataset after filling missing value:")
print(df)

total_sales = df["Amount"].sum()
print("\nTotal Sales:", total_sales)

sales_by_category = df.groupby("Category")["Amount"].sum()
print("\nSales by Category:")
print(sales_by_category)

karachi_orders = df[df["City"] == "Karachi"]
print("\nOrders from Karachi:")
print(karachi_orders)

avg_customer_sales = df.groupby("Customer")["Amount"].mean()
print("\nAverage Sales per Customer:")
print(avg_customer_sales)

import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, None, 2400, 5200, 15000]
}
df = pd.DataFrame(sales_data)

print("First 3 Rows:")
print(df.head(3))

print("\nMissing Values:")
print(df.isnull())
median_value = df["Amount"].median()
df["Amount"] = df["Amount"].fillna(median_value)

df["Amount"] = df["Amount"].astype(int)

print("\nCleaned Dataset:")
print(df)

df.to_csv("cleaned_sales_data.csv", index=False)

print("\nFile saved as cleaned_sales_data.csv")

import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, None, 2400, 5200, 15000]
}

df = pd.DataFrame(sales_data)

df["Amount"] = df["Amount"].fillna(df["Amount"].median())

df["HighValue"] = df["Amount"] > 10000
print("Dataset with HighValue column:")
print(df)

karachi_orders = df[df["City"] == "Karachi"]
print("\nOrders from Karachi:")
print(karachi_orders)

electronics_high = df[(df["Category"] == "Electronics") & (df["Amount"] > 10000)]
print("\nElectronics orders with Amount > 10000:")
print(electronics_high)

sorted_data = df.sort_values(by="Amount", ascending=False)
print("\nData sorted by Amount (Descending):")
print(sorted_data)

top_customers = df.groupby("Customer")["Amount"].sum().sort_values(ascending=False).head(2)
print("\nTop 2 Customers by Total Spending:")
print(top_customers)

import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, None, 2400, 5200, 15000]
}

df = pd.DataFrame(sales_data)

df["Amount"] = df["Amount"].fillna(df["Amount"].median())

revenue_city = df.groupby("City")["Amount"].sum()
print("Total Revenue per City:")
print(revenue_city)

avg_category = df.groupby("Category")["Amount"].mean()
print("\nAverage Order Amount per Category:")
print(avg_category)

unique_customers = df.groupby("City")["Customer"].nunique()
print("\nUnique Customers per City:")
print(unique_customers)

pivot = pd.pivot_table(df, values="Amount", index="City", columns="Category", aggfunc="sum")
print("\nPivot Table (City vs Category):")
print(pivot)

revenue_city_df = df.groupby("City")["Amount"].sum().reset_index()
print("\nRevenue per City with Reset Index:")
print(revenue_city_df)

import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, None, 2400, 5200, 15000]
}

df = pd.DataFrame(sales_data)

df["Amount"] = df["Amount"].fillna(df["Amount"].median())

df["TaxedAmount"] = df["Amount"] * 1.15

df["City"] = df["City"].str.lower()

df = df.sort_values(by="Amount", ascending=False)
df = df.drop_duplicates(subset="Customer", keep="first")

summary = {
    "total_orders": len(df),
    "total_revenue": df["Amount"].sum(),
    "average_order": df["Amount"].mean(),
    "top_city": df.groupby("City")["Amount"].sum().idxmax()
}

print("Summary Report:")
print(summary)

df.to_csv("final_sales_report.csv", index=False)

print("\nFinal dataset saved as final_sales_report.csv")