# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhqsKf_z3rV3X1ixQ4ONA366E-S2B6tq
"""

import numpy as np
import pandas as pd


student_data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Bilal", "Zara"],
    "Marks": [78, 92, None, 65, 45, 88],
    "Attendance": [80, 95, 70, None, 60, 98],
    "Department": ["CS", "IT", "CS", "SE", "IT", "CS"]
}

students_df = pd.DataFrame(student_data)

print("===== ORIGINAL DATA =====")
print(students_df)

students_df["Marks"] = students_df["Marks"].fillna(
    students_df["Marks"].mean()
)

students_df["Attendance"] = students_df["Attendance"].fillna(
    students_df["Attendance"].median()
)

print("\n===== AFTER FILLING MISSING VALUES =====")
print(students_df)
marks_array = np.array(students_df["Marks"])

print("\n===== NUMPY ARRAY =====")
print(marks_array)

percentage_array = marks_array / 100

print("\n===== PERCENTAGES =====")
print(percentage_array)

passed_students = marks_array[marks_array >= 50]

print("\n===== PASSED STUDENTS MARKS =====")
print(passed_students)

average_marks = np.mean(marks_array)

print("\nAverage Marks:", average_marks)

students_df["Passed"] = students_df["Marks"] >= 50

students_df["Percentage"] = students_df["Marks"] / 100

print("\n===== DATA WITH NEW COLUMNS =====")
print(students_df)


def grade_function(mark):
    if mark >= 85:
        return "A"
    elif mark >= 70:
        return "B"
    elif mark >= 50:
        return "C"
    else:
        return "Fail"

students_df["Grade"] = students_df["Marks"].apply(grade_function)

print("\n===== DATA WITH GRADES =====")
print(students_df)


high_scorers = students_df[students_df["Marks"] > 80]

print("\n===== HIGH SCORERS =====")
print(high_scorers)


filtered_students = students_df[
    (students_df["Marks"] > 60) &
    (students_df["Attendance"] > 75)
]

print("\n===== FILTERED STUDENTS =====")
print(filtered_students)



sorted_df = students_df.sort_values(
    by="Marks",
    ascending=False
)

print("\n===== SORTED DATA =====")
print(sorted_df)

# ==========================================
# STEP 8: LOC AND ILOC
# ==========================================

print("\n===== USING LOC =====")
print(students_df.loc[:, ["Name", "Marks"]])

print("\n===== USING ILOC =====")
print(students_df.iloc[0:3, 0:2])

# ==========================================
# STEP 9: GROUPBY AND AGGREGATION
# ==========================================

summary = students_df.groupby("Department").agg({
    "Marks": "mean",
    "Attendance": "mean"
})

print("\n===== DEPARTMENT SUMMARY =====")
print(summary)



students_df.to_csv(
    "processed_students.csv",
    index=False
)

print("\nProject Completed Successfully!")
print("CSV File Saved Successfully!")